# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 5
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.cache/wt [current_project]
set_property parent.project_path D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/Study/NTHU/3rd_Semester/HDL/Adv_Lab_4/Lab4_template/Lab4_template/Lab4_3_template/ip [current_project]
update_ip_catalog
set_property ip_output_repo d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Study/NTHU/3rd_Semester/HDL/FNAF/Picture/dist/door_8bit.coe
add_files D:/Study/NTHU/3rd_Semester/HDL/FNAF/Picture/dist/main_room_8bit.coe
add_files D:/Study/NTHU/3rd_Semester/HDL/FNAF/Picture/main_room.coe
add_files D:/Study/NTHU/3rd_Semester/HDL/FNAF/Picture/door.coe
add_files D:/Study/NTHU/3rd_Semester/HDL/FNAF/Picture/flash.coe
add_files D:/Study/NTHU/3rd_Semester/HDL/FNAF/Picture/bonnie_jumpscare.coe
add_files D:/Study/NTHU/3rd_Semester/HDL/FNAF/Picture/close_door.coe
add_files D:/Study/NTHU/3rd_Semester/HDL/FNAF/Picture/bonnie.coe
add_files D:/Study/NTHU/3rd_Semester/HDL/FNAF/Picture/chika.coe
add_files d:/Study/NTHU/3rd_Semester/HDL/FNAF/Picture/main_menu.coe
add_files d:/Study/NTHU/3rd_Semester/HDL/FNAF/Picture/win.coe
add_files d:/Study/NTHU/3rd_Semester/HDL/FNAF/Picture/lose.coe
read_verilog -library xil_defaultlib {
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/SevenSegment.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/audio_control.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/bonnie.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/chika.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/choose_nights.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/HDL/Adv_Lab_5/clock_divider.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/game_map.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/gameplay_countdown.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/gameplay_state.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/HDL/FNAF/jumpscare_control.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/keyboard_control.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/HDL/Adv_Lab_4/Lab4_template/Lab4_template/Lab4_3_template/keyboard_decoder.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/led_control.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/main_state.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/HDL/Adv_Lab_4/Lab4_template/Lab4_template/Lab4_3_template/note_gen.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/Lab4_3_template/onepulse.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/screen_controller.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/FNAF/seven_segment_display_control.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/HDL/Adv_Lab_4/Lab4_template/Lab4_template/Lab4_3_template/speaker_control.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/HDL/Adv_Lab_5/SampleCode_VGA/demo1/vga.v
  D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/imports/HDL/Adv_Lab_5/SampleCode_VGA/demo1/top.v
}
read_ip -quiet D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_3_1/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_3_1/blk_mem_gen_3_ooc.xdc]

read_ip -quiet D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0.xci

read_ip -quiet D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property used_in_implementation false [get_files -all d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc]

read_ip -quiet D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5.xci
set_property used_in_implementation false [get_files -all d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5_ooc.xdc]

read_ip -quiet d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6.xci
set_property used_in_implementation false [get_files -all d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6_ooc.xdc]

read_ip -quiet d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7.xci
set_property used_in_implementation false [get_files -all d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7_ooc.xdc]

read_ip -quiet d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8.xci
set_property used_in_implementation false [get_files -all d:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/constrs_1/imports/FNAF/FNAF_4_constraint.xdc
set_property used_in_implementation false [get_files D:/Study/NTHU/3rd_Semester/HDL/FNAF/FNAF/FNAF.srcs/constrs_1/imports/FNAF/FNAF_4_constraint.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top FNAF_4 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FNAF_4.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FNAF_4_utilization_synth.rpt -pb FNAF_4_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
